name: Python application

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
    - name: Lint
      run: |
        pylint product2vec
        pylint tests
        isort --check --diff product2vec
        isort --check --diff tests
        black --check --diff product2vec
        black --check --diff tests
    - name: Test
      run: |
        pytest tests --cov --cov-fail-under=90
